name = "todo-app-backend"
main = "src/worker.ts"
compatibility_date = "2024-08-01"

# Node.js互換フラグを追加（不要なモジュールエラーを回避）
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "todo-app-backend"

[env.staging]
name = "todo-app-backend-staging"

# Workers の環境変数（必要に応じて）
[vars]
ENVIRONMENT = "production"
