name: TodoApp CI/CD Pipeline

on: 
  push:
    branches: [main]

jobs: 
  build:
    name: Build Phase
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: todo-cicd/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: todo-cicd

      - name: Build application
        run: npm run build
        working-directory: todo-cicd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: build-files
          path: todo-cicd/dist/
          retention-days: 1

  test:
    name: Test Phase
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: "npm"
          cache-dependency-path: todo-cicd/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: todo-cicd

      - name: Run tests
        run: npm run test
        working-directory: todo-cicd