name: TodoApp CI/CD Pipeline

on: 
  push:
    branches: [main]

jobs: 
  build:
    name: Build Phase
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: todo-cicd/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: todo-cicd

      - name: Build application
        run: npm run build
        working-directory: todo-cicd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: build-files
          path: todo-cicd/dist/
          retention-days: 1

  test:
    name: Test Phase
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: "npm"
          cache-dependency-path: todo-cicd/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: todo-cicd

      - name: Run tests
        run: npm run test
        working-directory: todo-cicd

  deploy:
    name: Deploy Phase
    runs-on: ubuntu-latest
    needs: [build, test]

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: todo-cicd/dist/


      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install
        working-directory: todo-cicd

      - name: Prepare Google Application Credentials
        run: |
          echo "Creating credentials file..."
          if [ -z "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" ]; then
            echo "ERROR: GOOGLE_APPLICATION_CREDENTIALS secret is empty or not set!"
            exit 1
          fi
          echo "Secret length: ${#GOOGLE_APPLICATION_CREDENTIALS}"
          echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} | base64 --decode > /tmp/private-key.json
          echo "Credentials file created:"
          ls -la /tmp/private-key.json
          echo "File size: $(wc -c < /tmp/private-key.json) bytes"
          if [ -s /tmp/private-key.json ]; then
            echo "First few characters:"
            head -c 50 /tmp/private-key.json
          else
            echo "ERROR: Credentials file is empty!"
            exit 1
          fi

      - name: Test Firebase Authentication
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/private-key.json
        run: |
          echo "Testing Firebase authentication..."
          firebase projects:list
        working-directory: todo-cicd

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/private-key.json
        run: |
          firebase experiments:enable webframeworks
          firebase use cicd-todo-app-89c3b
          firebase deploy --only hosting --non-interactive
        working-directory: todo-cicd
      - name: Remove private key
        if: always()
        run: rm /tmp/private-key.json
